@baseUrl = http://localhost:3005

# @name health

GET {{baseUrl}}/health
Content-Type: application/json

###
GET {{baseUrl}}/health/live
Content-Type: application/json

###
GET {{baseUrl}}/health/ready
Content-Type: application/json

###
GET {{baseUrl}}/health/services
Content-Type: application/json

###
GET {{baseUrl}}/health/services/users
Content-Type: application/json

###
# # @name authenticate
# POST {{baseUrl}}/sessions
# Content-Type: application/json

# {
#     "email": "john.doe2@example.com",
#     "password": "securepassword123"
# }

